# Generated by Django 4.1 on 2023-11-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('content', models.TextField(blank=True, max_length=3000)),
                ('author', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
