# Generated by Django 4.1 on 2023-11-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_user_contactmodel_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
