# Generated by Django 4.1 on 2023-11-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blogmodel_options_alter_contactmodel_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='sender',
        ),
    ]
