# Generated by Django 4.1 on 2023-11-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_contactmodel_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={},
        ),
    ]
