# Generated by Django 4.2.7 on 2023-11-22 10:24

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blogmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='quill_content',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
